name: Add approved person to ppl.json

on:
  issues:
    types: [labeled]

permissions:
  contents: write

jobs:
  add-person:
    if: github.actor == 'tren03' && contains(github.event.issue.labels.*.name, 'approved')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract name and URL from issue
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.md
          name=$(grep -i '^Name:' issue_body.md | sed 's/Name:[[:space:]]*//')
          url=$(grep -i '^Profile URL:' issue_body.md | sed 's/Profile URL:[[:space:]]*//')
          echo "NAME=$name" >> $GITHUB_OUTPUT
          echo "URL=$url" >> $GITHUB_OUTPUT

      - name: Append to ppl.json
        run: |
          name="${{ steps.extract.outputs.NAME }}"
          url="${{ steps.extract.outputs.URL }}"
          timestamp=$(date +%s)
          date=$(date +%m/%d/%Y)
          slug=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')
          id="${slug}-${timestamp}"

          echo "Adding $name ($url) as $id"

          jq --arg name "$name" \
             --arg url "$url" \
             --arg id "$id" \
             --arg date "$date" \
             '. += [{"name": $name, "url": $url, "id": $id, "addedDate": $date}]' \
             frontend/src/data/ppl.json > tmp.json

          mv tmp.json frontend/src/data/ppl.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add frontend/src/data/ppl.json
          git commit -m "Add ${{ steps.extract.outputs.NAME }} via approved issue"
          git push
