name: Fetch CTF Links and Save JSON

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  merge-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get new links from sheets and refresh ctf.json
        working-directory: scripts
        run: python fetch_ctf.py

      - name: Commit and push updated ctf.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "ctf-bot"
          git config --global user.email "ctf-bot@example.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git pull origin main 
          git add frontend/src/data/ctf.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ctf JSON [bot]"
          git push
