name: Fetch YouTube Videos and Save JSON

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  fetch-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_youtube.py
        working-directory: scripts
        env:
          YT_API: ${{ secrets.YT_API }}
        run: python fetch_youtube.py

      - name: Fetch YouTube transcripts
        working-directory: scripts
        run: python fetch_yt_transcript.py

      - name: Generate summaries for YouTube videos
        working-directory: scripts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python -c "from summary_functions import process_yt_articles; process_yt_articles('../frontend/src/data/yt.json')"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "yt-bot"
          git config --global user.email "yt-bot@example.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add frontend/src/data/yt.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update YouTube JSON [bot]"
          git push
